version: '3.5'

services:

  flask:
    build:
      context: ./docker/flask
    depends_on: 
      - elastic
    container_name: cm_flask
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./src/flask:/app
    networks:
      backend:
        aliases:
          - cm_flask

  elastic:
    build:
      context: ./docker/elastic
      args:
        ELASTIC_VERSION: 7.5.0
    container_name: cm_elastic
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data/elastic/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    networks:
      backend:
        aliases:
          - cm_elastic

  # apache:
  #   build:
  #     context: docker/apache/.
  #   container_name: cm_apache
  #   restart: always
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./src/laravel:/var/www/localhost/htdocs
  #   networks:
  #     backend:
  #       aliases:
  #       - cm_apache

  # mysql:
  #   image: mysql:8.0
  #   container_name: cm_mysql
  #   restart: always
  #   ports:
  #     - 3307:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=car_manager
  #   command: --default-authentication-plugin=mysql_native_password
  #   volumes:
  #     - ./data/mysql:/var/lib/mysql
  #   networks:
  #     backend:
  #       aliases:
  #         - cm_mysql

networks:
  backend:
    name: cm_network