version: '3.5'

services:
  apache:
    build:
      context: docker/apache/.
    container_name: car_manager_apache
    ports:
      - 8080:80
    volumes:
      - ./src/laravel:/var/www/localhost/htdocs
    networks:
      backend:
        aliases:
        - car_manager_apache

  mysql:
    image: mysql:8.0
    container_name: car_manager_mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=car_manager
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      backend:
        aliases:
          - car_manager_mysql
          
networks:
  backend:
    name: car_manager_network