version: '3.5'

services:

  flask:
    build:
      context: ./docker/flask
    depends_on: 
      - redis
    container_name: cm_flask
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./src/flask:/app
    networks:
      backend:
        aliases:
          - cm_flask

  redis:
    image: redis:5.0
    container_name: cm_redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    networks:
      backend:
        aliases:
          - cm_redis

  apache:
    build:
      context: docker/apache/.
    container_name: cm_apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./src/laravel:/var/www/localhost/htdocs
    networks:
      backend:
        aliases:
        - cm_apache

  mysql:
    image: mysql:8.0
    container_name: cm_mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=car_manager
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      backend:
        aliases:
          - cm_mysql

networks:
  backend:
    name: cm_network