version: "3.5"

services:
  flask:
    build:
      context: ./docker/flask
    container_name: bc_flask
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
    networks:
      backend:
        aliases:
          - bc_flask
  redis:
    image: redis:5.0
    container_name: bc_redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    networks:
      backend:
        aliases:
          - bc_redis

networks:
  backend:
    name: bc_network